import type {
  AlertConfigSnapshot,
  AlertDashboard,
  AlertRuleset,
  ChartPoint,
  ConfigSnapshot,
  FileItem,
  FileNode,
  HeroCopy,
  MetricCard,
  MonitorNote,
  MonitorSummary,
  SystemOverview,
  SystemProcess,
  SystemResourceGauge,
  SystemVolume,
  UploadRecord,
} from "./types";

export const heroCopy: HeroCopy = {
  agent: "srv-01",
  watchDirs: ["/data/logs/app", "/data/etl/raw"],
  suffixFilter: "关闭 · 全量目录",
  silence: "4s",
  queue: "队列 200",
  concurrency: "上传并发 8",
};

export const metricCards: MetricCard[] = [
  { label: "运行状态", value: "Running", trend: "心跳正常", tone: "up" },
  { label: "今日上传", value: "248", trend: "+12%", tone: "up" },
  { label: "失败率", value: "1.4%", trend: "-0.3%", tone: "down" },
  { label: "队列深度", value: "32", trend: "背压监控", tone: "warning" },
  { label: "平均耗时", value: "820 ms", trend: "-90 ms", tone: "up" },
];

export const directoryTree: FileNode[] = [
  {
    name: "/data/logs/app",
    path: "/data/logs/app",
    type: "dir",
    autoUpload: true,
    children: [
      {
        name: "app-2024-12-26.log",
        path: "/data/logs/app/app-2024-12-26.log",
        type: "file",
        size: "14.2 MB",
        updated: "10:32:10",
        autoUpload: true,
      },
      {
        name: "heap-2024-12-26.hprof",
        path: "/data/logs/app/heap-2024-12-26.hprof",
        type: "file",
        size: "1.2 GB",
        updated: "10:31:45",
        autoUpload: false,
      },
      {
        name: "archived",
        path: "/data/logs/app/archived",
        type: "dir",
        autoUpload: false,
        children: [
          {
            name: "trace-2024-12-24.log",
            path: "/data/logs/app/archived/trace-2024-12-24.log",
            type: "file",
            size: "4.2 MB",
            updated: "10:20:12",
            autoUpload: false,
          },
          {
            name: "trace-2024-12-25.log",
            path: "/data/logs/app/archived/trace-2024-12-25.log",
            type: "file",
            size: "4.5 MB",
            updated: "10:28:18",
            autoUpload: true,
          },
        ],
      },
    ],
  },
  {
    name: "/data/etl/raw",
    path: "/data/etl/raw",
    type: "dir",
    autoUpload: true,
    children: [
      {
        name: "etl-raw-2024-12-26-01.csv",
        path: "/data/etl/raw/etl-raw-2024-12-26-01.csv",
        type: "file",
        size: "8.6 MB",
        updated: "10:31:58",
        autoUpload: true,
      },
      {
        name: "etl-raw-2024-12-26-02.csv",
        path: "/data/etl/raw/etl-raw-2024-12-26-02.csv",
        type: "file",
        size: "9.1 MB",
        updated: "10:29:31",
        autoUpload: true,
      },
      {
        name: "error-2024-12-26.tar.gz",
        path: "/data/etl/raw/error-2024-12-26.tar.gz",
        type: "file",
        size: "380 MB",
        updated: "10:30:02",
        autoUpload: false,
      },
    ],
  },
];

export const files: FileItem[] = [
  {
    name: "app-2024-12-26.log",
    path: "/data/logs/app/app-2024-12-26.log",
    size: "14.2 MB",
    status: "uploaded",
    time: "10:32:10",
    autoUpload: true,
  },
  {
    name: "etl-raw-2024-12-26-01.csv",
    path: "/data/etl/raw/etl-raw-2024-12-26-01.csv",
    size: "8.6 MB",
    status: "uploaded",
    time: "10:31:58",
    autoUpload: true,
  },
  {
    name: "heap-2024-12-26.hprof",
    path: "/data/logs/app/heap-2024-12-26.hprof",
    size: "1.2 GB",
    status: "queued",
    time: "10:31:45",
    autoUpload: false,
  },
  {
    name: "vid-2301.mp4",
    path: "/data/logs/app/vid-2301.mp4",
    size: "92 MB",
    status: "failed",
    time: "10:31:12",
    autoUpload: false,
  },
  {
    name: "error-2024-12-26.tar.gz",
    path: "/data/etl/raw/error-2024-12-26.tar.gz",
    size: "380 MB",
    status: "queued",
    time: "10:30:02",
    autoUpload: false,
  },
  {
    name: "model-v12.zip",
    path: "/data/logs/app/model-v12.zip",
    size: "482 MB",
    status: "uploaded",
    time: "10:30:44",
    autoUpload: true,
  },
];

export const monitorNotes: MonitorNote[] = [
  { title: "S3 连接", detail: "endpoint=minio.local · force_path_style=true · region=us-east-1" },
  { title: "上传工作池", detail: "workers=8 · queue=200 · 当前 backlog=32" },
  { title: "通知", detail: "钉钉机器人已配置 · 失败自动重试 3 次" },
];

export const uploadRecords: UploadRecord[] = [
  {
    file: "app-2024-12-26.log",
    target: "https://minio.local/logs-warm/app-2024-12-26.log",
    size: "14.2 MB",
    result: "success",
    latency: "640 ms",
    time: "10:32:10",
    note: "自动上传",
  },
  {
    file: "etl-raw-2024-12-26-01.csv",
    target: "https://minio.local/etl-raw/etl-raw-2024-12-26-01.csv",
    size: "8.6 MB",
    result: "success",
    latency: "520 ms",
    time: "10:31:58",
    note: "校验通过",
  },
  {
    file: "heap-2024-12-26.hprof",
    target: "",
    size: "1.2 GB",
    result: "pending",
    latency: "排队",
    time: "10:31:45",
    note: "排队中",
  },
  {
    file: "vid-2301.mp4",
    target: "",
    size: "92 MB",
    result: "failed",
    latency: "timeout",
    time: "10:31:12",
    note: "已触发告警",
  },
  {
    file: "model-v12.zip",
    target: "https://minio.local/artifacts/model-v12.zip",
    size: "482 MB",
    result: "success",
    latency: "2.4 s",
    time: "10:30:44",
    note: "断点续传",
  },
];

export const monitorSummary: MonitorSummary[] = [
  { label: "当前吞吐", value: "480/min", desc: "峰值 520/min" },
  { label: "成功率", value: "98.6%", desc: "失败率 1.4%" },
  { label: "平均延迟", value: "820 ms", desc: "P95 1.4s" },
  { label: "队列 backlog", value: "32", desc: "workers=8 / retry=3" },
];

// 过滤示例配置
export const configSnapshot: ConfigSnapshot = {
  watchDir: "/data/logs/app , /data/etl/raw",
  fileExt: "关闭 · 全量目录",
  silence: "4s",
  concurrency: "workers=8 / queue=200",
  uploadRetryDelays: "1s,2s,5s",
  uploadRetryEnabled: true,
  systemResourceEnabled: false,
};

export const alertConfigSnapshot: AlertConfigSnapshot = {
  enabled: true,
  suppressEnabled: true,
  rulesFile: "/etc/gwf/alert-rules.yaml",
  logPaths: "/var/log/app/error.log,/var/log/app/worker.error.log",
  pollInterval: "2s",
  startFromEnd: true,
};

export const alertRulesSnapshot: AlertRuleset = {
  version: 1,
  defaults: {
    suppress_window: "5m",
    match_case: false,
  },
  escalation: {
    enabled: true,
    level: "fatal",
    window: "5m",
    threshold: 20,
    suppress_window: "5m",
    rule_id: "system_spike",
    title: "系统异常激增",
    message: "系统异常在5分钟内达到20次",
  },
  rules: [
    {
      id: "ignore_debug",
      title: "忽略调试噪音",
      level: "ignore",
      keywords: ["debug", "trace", "heartbeat"],
      excludes: ["fatal", "system"],
    },
    {
      id: "biz_validate",
      title: "业务参数校验失败",
      level: "business",
      keywords: ["手机号无效", "参数校验失败", "validation failed"],
      notify: false,
      suppress_window: "10m",
    },
    {
      id: "system_db",
      title: "数据库连接异常",
      level: "system",
      keywords: ["Connection is not available", "连接池耗尽", "timeout"],
      notify: true,
    },
    {
      id: "fatal_oom",
      title: "内存溢出",
      level: "fatal",
      keywords: ["OutOfMemoryError", "Java heap space", "内存溢出"],
      notify: true,
    },
  ],
};

export const chartPoints: ChartPoint[] = [
  { label: "02:00", uploads: 40, failures: 2, queue: 20 },
  { label: "04:00", uploads: 52, failures: 1, queue: 34 },
  { label: "06:00", uploads: 60, failures: 3, queue: 40 },
  { label: "08:00", uploads: 78, failures: 4, queue: 52 },
  { label: "10:00", uploads: 92, failures: 2, queue: 38 },
  { label: "12:00", uploads: 88, failures: 3, queue: 32 },
];

export const alertDashboard: AlertDashboard = {
  overview: {
    window: "最近30分钟",
    risk: "高",
    fatal: 1,
    system: 6,
    business: 12,
    sent: 8,
    suppressed: 14,
    latest: "2025-01-08 22:33:05",
  },
  decisions: [
    {
      id: "1",
      time: "2025-01-08 22:33:05",
      level: "fatal",
      rule: "系统异常激增",
      message: "系统异常在5分钟内达到20次",
      file: "-",
      status: "sent",
    },
    {
      id: "2",
      time: "2025-01-08 22:32:41",
      level: "system",
      rule: "数据库连接池耗尽",
      message: "HikariPool-1 - Connection is not available",
      file: "/var/log/app/error.log",
      status: "sent",
    },
    {
      id: "3",
      time: "2025-01-08 22:32:30",
      level: "system",
      rule: "线程池拒绝",
      message: "RejectedExecutionException: thread pool is exhausted",
      file: "/var/log/app/error.log",
      status: "suppressed",
      reason: "5分钟内已告警",
    },
    {
      id: "4",
      time: "2025-01-08 22:32:22",
      level: "business",
      rule: "订单落库失败",
      message: "order write failed: duplicate key",
      file: "/var/log/app/error.log",
      status: "recorded",
    },
    {
      id: "5",
      time: "2025-01-08 22:31:58",
      level: "system",
      rule: "磁盘写入异常",
      message: "I/O error on device /dev/nvme0n1",
      file: "/var/log/app/error.log",
      status: "suppressed",
      reason: "5分钟内已告警",
    },
  ],
  stats: {
    sent: 8,
    suppressed: 14,
    recorded: 5,
  },
  rules: {
    source: "/etc/gwf/alert-rules.yaml",
    lastLoaded: "2025-01-08 22:33:00",
    total: 12,
    defaultSuppress: "5分钟",
    escalation: "阈值20次 / 5分钟 -> fatal",
    levels: {
      ignore: 2,
      business: 4,
      system: 5,
      fatal: 1,
    },
  },
  polling: {
    interval: "2s",
    logFiles: ["/var/log/app/error.log", "/var/log/app/worker.error.log"],
    lastPoll: "2025-01-08 22:33:04",
    nextPoll: "2025-01-08 22:33:06",
  },
};

export const systemOverview: SystemOverview = {
  host: "srv-01",
  os: "Ubuntu 22.04.4 LTS",
  kernel: "6.2.0-34-generic",
  uptime: "3天 6小时 21分",
  load: "1.18 / 1.32 / 1.48",
  ip: "10.2.14.8",
  lastUpdated: "10:42:18",
  processes: 186,
  connections: 92,
  connectionsBreakdown: "ESTABLISHED 68 · TIME_WAIT 12",
  cpuTemp: "62°C",
  topProcess: "java",
};

export const systemGauges: SystemResourceGauge[] = [
  {
    id: "cpu",
    label: "CPU 使用率",
    usedPct: 68,
    usedLabel: "68%",
    totalLabel: "16 核 · 3.6 GHz",
    subLabel: "负载 1.18 / 1.32 / 1.48",
    trend: "峰值 74% · 温度 62°C",
    tone: "warn",
  },
  {
    id: "memory",
    label: "内存占用",
    usedPct: 54,
    usedLabel: "34.7 GB",
    totalLabel: "总计 64 GB",
    subLabel: "缓存 8.1 GB · 交换 2.3/8 GB",
    trend: "过去 5 分钟 +3%",
    tone: "normal",
  },
  {
    id: "disk",
    label: "磁盘占用",
    usedPct: 76,
    usedLabel: "1.8 TB",
    totalLabel: "总计 2.4 TB",
    subLabel: "读取 86 MB/s · 写入 120 MB/s",
    trend: "IOPS 3.2k · 队列 1.4",
    tone: "critical",
  },
];

export const systemVolumes: SystemVolume[] = [
  { mount: "/", usedPct: 64, used: "320 GB", total: "500 GB" },
  { mount: "/data", usedPct: 82, used: "1.2 TB", total: "1.5 TB" },
  { mount: "/var/lib/docker", usedPct: 58, used: "180 GB", total: "310 GB" },
];

export const systemProcesses: SystemProcess[] = [
  {
    pid: 3241,
    name: "java",
    command: "/usr/bin/java -Xms4g -Xmx8g -jar app-service.jar",
    user: "app",
    status: "running",
    cpu: 46.2,
    mem: 28.9,
    rss: "6.4 GB",
    threads: 96,
    start: "08:12:01",
    uptime: "2天 4小时",
    ports: ["0.0.0.0:8080", "127.0.0.1:5005"],
    ioRead: "38 MB/s",
    ioWrite: "22 MB/s",
    netIn: "4.2 MB/s",
    netOut: "3.8 MB/s",
    cwd: "/opt/app",
    path: "/usr/bin/java",
    env: ["JAVA_OPTS=-Xmx8g", "SPRING_PROFILES_ACTIVE=prod", "TZ=Asia/Shanghai"],
    note: "高 CPU 负载",
  },
  {
    pid: 1820,
    name: "postgres",
    command: "/usr/lib/postgresql/14/bin/postgres -D /var/lib/postgresql/14/main",
    user: "postgres",
    status: "running",
    cpu: 24.8,
    mem: 12.6,
    rss: "2.4 GB",
    threads: 42,
    start: "06:10:22",
    uptime: "3天 6小时",
    ports: ["0.0.0.0:5432"],
    ioRead: "24 MB/s",
    ioWrite: "31 MB/s",
    netIn: "1.8 MB/s",
    netOut: "2.4 MB/s",
    cwd: "/var/lib/postgresql",
    path: "/usr/lib/postgresql/14/bin/postgres",
    env: ["PGDATA=/var/lib/postgresql/14/main", "LANG=en_US.UTF-8"],
  },
  {
    pid: 2318,
    name: "gwf-agent",
    command: "/usr/local/bin/gwf-agent --config /etc/gwf/agent.yaml",
    user: "gwf",
    status: "running",
    cpu: 12.4,
    mem: 3.2,
    rss: "420 MB",
    threads: 24,
    start: "09:40:12",
    uptime: "1天 1小时",
    ports: ["127.0.0.1:19090"],
    ioRead: "8 MB/s",
    ioWrite: "6 MB/s",
    netIn: "320 KB/s",
    netOut: "640 KB/s",
    cwd: "/var/lib/gwf",
    path: "/usr/local/bin/gwf-agent",
    env: ["GWF_ENV=prod", "GWF_REGION=cn-north-1"],
  },
  {
    pid: 1450,
    name: "node",
    command: "/usr/bin/node /srv/dashboard/server.js",
    user: "node",
    status: "running",
    cpu: 18.7,
    mem: 7.4,
    rss: "1.3 GB",
    threads: 18,
    start: "09:02:45",
    uptime: "1天 5小时",
    ports: ["0.0.0.0:3000"],
    ioRead: "6 MB/s",
    ioWrite: "4 MB/s",
    netIn: "2.2 MB/s",
    netOut: "1.9 MB/s",
    cwd: "/srv/dashboard",
    path: "/usr/bin/node",
    env: ["NODE_ENV=production", "PORT=3000"],
  },
  {
    pid: 966,
    name: "redis-server",
    command: "/usr/bin/redis-server 0.0.0.0:6379",
    user: "redis",
    status: "running",
    cpu: 6.2,
    mem: 1.8,
    rss: "980 MB",
    threads: 6,
    start: "07:22:30",
    uptime: "3天 2小时",
    ports: ["0.0.0.0:6379"],
    ioRead: "4 MB/s",
    ioWrite: "3 MB/s",
    netIn: "920 KB/s",
    netOut: "1.1 MB/s",
    cwd: "/var/lib/redis",
    path: "/usr/bin/redis-server",
    env: ["REDIS_MAXMEMORY=2gb", "REDIS_APPENDONLY=yes"],
  },
  {
    pid: 812,
    name: "nginx",
    command: "nginx: master process /usr/sbin/nginx -g daemon on;",
    user: "root",
    status: "running",
    cpu: 2.3,
    mem: 0.6,
    rss: "120 MB",
    threads: 8,
    start: "06:08:12",
    uptime: "3天 6小时",
    ports: ["0.0.0.0:80", "0.0.0.0:443"],
    ioRead: "2 MB/s",
    ioWrite: "1.6 MB/s",
    netIn: "3.1 MB/s",
    netOut: "2.8 MB/s",
    cwd: "/",
    path: "/usr/sbin/nginx",
    env: ["NGINX_WORKER_PROCESSES=auto"],
  },
  {
    pid: 2890,
    name: "prometheus",
    command: "/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml",
    user: "monitor",
    status: "running",
    cpu: 7.8,
    mem: 4.6,
    rss: "820 MB",
    threads: 16,
    start: "08:40:20",
    uptime: "2天 3小时",
    ports: ["0.0.0.0:9090"],
    ioRead: "5 MB/s",
    ioWrite: "7 MB/s",
    netIn: "1.2 MB/s",
    netOut: "1.6 MB/s",
    cwd: "/var/lib/prometheus",
    path: "/usr/local/bin/prometheus",
    env: ["PROMETHEUS_RETENTION=15d"],
  },
  {
    pid: 3012,
    name: "grafana-server",
    command: "/usr/sbin/grafana-server --config /etc/grafana/grafana.ini",
    user: "grafana",
    status: "running",
    cpu: 3.1,
    mem: 2.1,
    rss: "540 MB",
    threads: 14,
    start: "08:42:10",
    uptime: "2天 3小时",
    ports: ["0.0.0.0:3001"],
    ioRead: "1.2 MB/s",
    ioWrite: "900 KB/s",
    netIn: "640 KB/s",
    netOut: "520 KB/s",
    cwd: "/usr/share/grafana",
    path: "/usr/sbin/grafana-server",
    env: ["GF_SERVER_HTTP_PORT=3001"],
  },
  {
    pid: 1622,
    name: "python",
    command: "/usr/bin/python /opt/jobs/etl_sync.py --interval 5m",
    user: "etl",
    status: "running",
    cpu: 9.5,
    mem: 1.1,
    rss: "280 MB",
    threads: 10,
    start: "10:01:05",
    uptime: "8小时",
    ports: [],
    ioRead: "9 MB/s",
    ioWrite: "12 MB/s",
    netIn: "120 KB/s",
    netOut: "300 KB/s",
    cwd: "/opt/jobs",
    path: "/usr/bin/python",
    env: ["PYTHONUNBUFFERED=1", "ETL_REGION=cn-north-1"],
  },
  {
    pid: 1184,
    name: "docker-proxy",
    command: "/usr/bin/docker-proxy -proto tcp -host-port 9100",
    user: "root",
    status: "sleeping",
    cpu: 0.8,
    mem: 0.3,
    rss: "35 MB",
    threads: 4,
    start: "06:45:30",
    uptime: "3天 4小时",
    ports: ["0.0.0.0:9100"],
    ioRead: "120 KB/s",
    ioWrite: "80 KB/s",
    netIn: "90 KB/s",
    netOut: "120 KB/s",
    cwd: "/",
    path: "/usr/bin/docker-proxy",
    env: ["DOCKER_HOST=unix:///var/run/docker.sock"],
  },
  {
    pid: 402,
    name: "rsyslogd",
    command: "/usr/sbin/rsyslogd -n -iNONE",
    user: "syslog",
    status: "sleeping",
    cpu: 0.2,
    mem: 0.2,
    rss: "48 MB",
    threads: 3,
    start: "06:41:50",
    uptime: "3天 6小时",
    ports: [],
    ioRead: "220 KB/s",
    ioWrite: "180 KB/s",
    netIn: "0 KB/s",
    netOut: "0 KB/s",
    cwd: "/",
    path: "/usr/sbin/rsyslogd",
    env: ["LANG=C", "RSYSLOG_DEFAULT_RULESET=main"],
  },
  {
    pid: 276,
    name: "containerd",
    command: "/usr/bin/containerd",
    user: "root",
    status: "running",
    cpu: 1.1,
    mem: 0.9,
    rss: "210 MB",
    threads: 22,
    start: "06:40:12",
    uptime: "3天 6小时",
    ports: [],
    ioRead: "1.1 MB/s",
    ioWrite: "1.3 MB/s",
    netIn: "60 KB/s",
    netOut: "70 KB/s",
    cwd: "/",
    path: "/usr/bin/containerd",
    env: ["CONTAINERD_LOG_LEVEL=info"],
  },
];
